name: py

on: push    #runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
      # - name: Trying python script
      #   uses: jannekem/run-python-script-action@v1
      #   with:
      #     script: |
      #       import os
      #       print("Directory contents:")
      #       for f in os.listdir():
      #           print(f)
        with:
          python-version: 3.8
      - name: Custom
        run: |
          # cd GiftcardSite
          # sudo apt-get install python3-venv
          # python3 -m venv .
          # sudo pip3 install virtualenvwrapper
          # export WORKON_HOME=$HOME/.virtualenvs
          # export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
          # export VIRTUALENVWRAPPER_VIRTUALENV_ARGS=' -p /usr/bin/python3 '
          # export PROJECT_HOME=$HOME/Devel
          # source /usr/local/bin/virtualenvwrapper.sh
          python3 -m pip install Django
          echo $PATH
          echo $PYTHONPATH
          python3 -c 'import django'
          # echo 'done 0'
          # python3 manage.py makemigrations LegacySite
          # echo 'done 1'
          # python3 manage.py migrate
          # echo 'done 2'
          # python3 -m pip install Django
          # sudo python3 manage.py runserver 80
          # echo 'done 3'

