name: py

on: push    #runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
      - uses: jannekem/run-python-script-action@v1
        with:
          python-version: 3.8 #install the python needed
          script: |
            print("Done")

