name: py

on: push    #runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          run: |
            print("Done")

