name: py

on: push    #runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Custom
        run: |
          python ank8821-xss.py

