name: py

on: push    #runs on push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2 
      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run the server
        run: |
          cd GiftcardSite
          sudo python3 -m pip install Django
          sudo python3 -c 'import django'
          sudo python3 manage.py makemigrations LegacySite
          sudo python3 manage.py migrate
          sudo python3 manage.py runserver 80 &
          pid=$!
        env:
          process_id: $pid
      - name: Kill the server
        run: |
            echo ${{ env.process_id }}
#           echo $pid
#           sudo kill $pid
#           echo "killed"

