name: py

on: push    #runs at 11:30 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 
      - name: Setup python
        uses: actions/setup-python@v2
      # - name: Trying python script
      #   uses: jannekem/run-python-script-action@v1
      #   with:
      #     script: |
      #       import os
      #       print("Directory contents:")
      #       for f in os.listdir():
      #           print(f)
        with:
          python-version: 3.8
      - name: Custom
        run: |
          cd GiftcardSite
          # python -m pip install django
          python manage.py makemigrations LegacySite
          python manage.py migrate
          python manage.py runserver 80

