name: Vulnerability Checker

on: push  # runs on push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2 
      - name: Setup python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run the server
        run: |
          cd GiftcardSite
          sudo python3 -m pip install Django
          sudo python3 -m pip install django-encrypted-model-fields
          sudo python3 manage.py makemigrations LegacySite
          sudo python3 manage.py migrate
          sudo python3 manage.py runserver 80 &
      - name: Checking for XXS Vulnerability
        run: |
          sudo python3 ank8821-xss.py
      - name: Checking for CSRF Vulnerability
        run: |
          sudo python3 ank8821-csrf.py
      - name: Checking for SQLi Vulnerability
        run: |
          sudo python3 ank8821-sqli.py
      - name: Checking for CMDi Vulnerability
        run: |
          sudo python3 ank8821-cmdi.py
      - name: Killing server
        run: |
          sudo kill $(sudo ps aux | grep -m1 'sudo python3' | awk -F ' '  '{print $2}')
